package CalculatorIDL;


/**
* CalculatorIDL/CalculateThisShitPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculator.idl
* Wednesday, November 28, 2012 2:18:40 PM CET
*/

public abstract class CalculateThisShitPOA extends org.omg.PortableServer.Servant
 implements CalculatorIDL.CalculateThisShitOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("calculate", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // CalculatorIDL/CalculateThisShit/calculate
       {
         String input = in.read_string ();
         double $result = (double)0;
         $result = this.calculate (input);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CalculatorIDL/CalculateThisShit:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public CalculateThisShit _this() 
  {
    return CalculateThisShitHelper.narrow(
    super._this_object());
  }

  public CalculateThisShit _this(org.omg.CORBA.ORB orb) 
  {
    return CalculateThisShitHelper.narrow(
    super._this_object(orb));
  }


} // class CalculateThisShitPOA
