package CalculatorIDL;


/**
* CalculatorIDL/CalculateThisShit.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculator.idl
* Wednesday, November 28, 2012 2:18:40 PM CET
*/

public interface CalculateThisShit extends CalculateThisShitOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CalculateThisShit
