package MainServer.Model.JokesIDL;


/**
* jokes/JokesOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from jokes.idl
* Wednesday, November 28, 2012 11:54:27 AM CET
*/

public interface JokesOperations 
{
  String send_joke ();
} // interface JokesOperations
