/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CalcFunc */

#ifndef _Included_CalcFunc
#define _Included_CalcFunc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CalcFunc
 * Method:    sum
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_CalcFunc_sum
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     CalcFunc
 * Method:    subtract
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_CalcFunc_subtract
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     CalcFunc
 * Method:    multiply
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_CalcFunc_multiply
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     CalcFunc
 * Method:    divide
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_CalcFunc_divide
  (JNIEnv *, jclass, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
