package JokesServer.Model.JokesIDL;


/**
* jokes/_JokesStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from jokes.idl
* Wednesday, November 28, 2012 11:54:27 AM CET
*/

public class _JokesStub extends org.omg.CORBA.portable.ObjectImpl implements JokesServer.Model.JokesIDL.Jokes
{

  public String send_joke ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("send_joke", true);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return send_joke (        );
            } finally {
                _releaseReply ($in);
            }
  } // send_joke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:jokes/Jokes:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init (args, props).string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     String str = org.omg.CORBA.ORB.init (args, props).object_to_string (this);
     s.writeUTF (str);
  }
} // class _JokesStub
