package JokesServer.Model.JokesIDL;


/**
* jokes/Jokes.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from jokes.idl
* Wednesday, November 28, 2012 11:54:27 AM CET
*/

public interface Jokes extends JokesOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Jokes
