package MainServer.Model.CalculatorIDL;


/**
* CalculatorIDL/CalculateThisShitOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculator.idl
* Wednesday, November 28, 2012 2:18:40 PM CET
*/

public interface CalculateThisShitOperations 
{
  double calculate (String input);
} // interface CalculateThisShitOperations
